refactor: refactor given code
gugu-book-salon/grokking-simplicity pull request #6
Opened 2022-07-25 16:42 UTC by ChobobDev

I have completed tasks from week 1.

Thank you

2022-07-26 02:53 UTC, woori3104 commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  return (item.style.display = "block");
이건 결국 중복함수아닌가요? 
굳이 이렇게까지 나눌필요는 없을거같아여

2022-07-26 02:53 UTC, woori3104 commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +      filterItem(filter);
filterItem이라는 이름에서 가격합산, 화면에 출력까지하고있는데 
이 함수이름에서는 상기 내용을 유추하기 힘들지않을까여?

2022-07-26 05:34 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +cmain();
main!!

2022-07-26 05:34 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +function setStyleNone(item) {
setStyleNone, setStlyeBlock 그냥 setStyle로 합쳐도 될듯해요 none이랑 block은 인자로 넣고!

2022-07-26 05:34 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +function filterItem(selectedItem) {
함수 이름은 filter 로직과 상관 없고 이벤트 사이드이펙트에 좀더 가까운거같아서 이름변경이 필요합니다

2022-07-26 05:34 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  let sum = 0;
변수하나 더쓰기보단 reduce로 sum로직을 수행하고 sum로직과 display로직을 분리하는게 더 좋아보여요

2022-07-26 05:54 UTC, ForestLee0513 requested changes

2022-07-26 05:54 UTC, ForestLee0513 commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  return a + b;
해당 함수 자체는 다른 상황에서도 충분히 사용할 수 있는데, 네이밍이 그걸 막으려고 하고 있네요.
네이밍만 바뀌면 더 좋을 듯 합니다.

2022-07-26 22:08 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  return (item.style.display = "block");
리뷰 받고 보니 정말 무의미 한거 같네요, 수정해보겠습니다

2022-07-26 22:08 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +cmain();
확인하지 않고 커밋한게 부끄럽네요, 수정하겠습니다.

2022-07-26 22:17 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  return a + b;
확실히 네이밍이 함수형 프로그래밍의 이유인 재사용성에 위배되는거 같네요, 수정해보겠습니다

2022-07-26 22:18 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +function filterItem(selectedItem) {
네 확실히 함수명 변경이 필요한것 같네요, 수정해보겠습니다.

2022-07-26 22:19 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +function setStyleNone(item) {
생각해 보니 그렇네요, 이 부분도 수정해 보겠습니다.

2022-07-26 22:21 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +      filterItem(filter);
확실히 함수명이 함수의 기능을 유추할수 없게 하는것 같네요, 수정해보겠습니다.

2022-08-01 04:33 UTC, hyunjaesung approved these changes

2022-08-01 04:33 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  //reduce 함수 구현
아 언제하냐공

2022-08-01 15:25 UTC, jungwoonlim commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  return (item.style.display = style);
여기엔 return이 빠지면 좋을거 같아요.

2022-08-04 05:55 UTC, ChobobDev commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  //reduce 함수 구현
오늘 마무리해서 제출 하겠습니닷

2022-08-05 10:40 UTC, hyunjaesung commented on 1주차/띠비/답자랑/뻐드렁니/answer.js
> +  const totalPrice = Array.from(storeItems).reduce((acc, el, i, src) => {
따로 변수로 안빼고 바로 리턴해도 될거같아요 또 팁주자면 [...storeItems] 해도 배열로 바뀝니다

2022-08-05 11:06 UTC, merged